---
- name: Install jdk 8
  package:
    name: java-1.8.0-openjdk
    state: present
  when: jfmc_install_jdk8

- name: "Set JAVA Environment Variables"
  lineinfile:
    dest: /etc/environment
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^JAVA_HOME=", line: "JAVA_HOME=/usr/java/jdk1.1.8.0.0_{{ jdk_update }}" }
    - { regexp: "^JRE_HOME=", line: "JRE_HOME=/usr/java/jdk1.1.8.0.0_{{ jdk_update }}/jre" }