---

- name: Configure java
  include_tasks: configure_java.yml
  when: jfmc_install_jdk8

- name: Install openssl
  package:
    name: openssl 
    state: present

- name: Install PHP
  package:
    name: php.x86_64
    state: present

- name: Install PHP FastCGI Process Manager
  package:
    name: php-fpm 
    state: present

- name: Install net-tools
  package:
    name: net-tools 
    state: present