---

- name: Install yum dependencies
  include_tasks: get_yum_dependencies.yml

- name: Creates mission-control directory 
  file:
    path: /opt/jfrog/mission-control/installer
    state: directory

- name: Extract mission control .tar
  unarchive:
    src: https://github.com/stone-payments/ansible-jfrog-mission-control/releases/download/v0.1-alpha/jfmc-redhat-2.1.1.tar.gz
    dest: /opt/jfrog/mission-control/installer
    remote_src: yes
    creates: /opt/jfrog/mission-control/installer/jfmc-redhat-2.1.1

# TODO: Edit script to allow selinux enforcing
- name: Allow MongoDB to listen on tcp port 27017 (SELinux)
  seport:
    ports: 27017
    proto: tcp
    setype: mongod_port_t
    state: present
    reload: yes
  when: jfmc_mongodb_semanage

# - selinux_permissive:
#   name: mongod_t
#   permissive: true