---

- name: Install yum dependencies
  include_tasks: get_yum_dependencies.yml

- name: Creates mission-control directory 
  file:
    path: /opt/jfrog/mission-control/installer
    state: directory

- name: Extract mission control .tar
  unarchive:
    src: https://github.com/stone-payments/ansible-jfrog-mission-control/releases/download/v0.1-alpha/jfmc-redhat-2.1.1.tar.gz
    dest: /opt/jfrog/mission-control/installer
    remote_src: yes
    creates: /opt/jfrog/mission-control/installer/jfmc-redhat-2.1.1

- name: Remove original shell script installer
  file:
    path: /opt/jfrog/mission-control/installer/jfmc-redhat-2.1.1/installJFMC-redhat.sh
    state: absent

- name: Generate install script
  template:
    src: ../templates/installJFMC-redhat.sh
    dest: /opt/jfrog/mission-control/installer/jfmc-redhat-2.1.1/ansible_installJFMC-redhat.sh
    mode: 0755

- name: Allow MongoDB to listen on tcp port 27017 (SELinux rule)
  seport:
    ports: 27017
    proto: tcp
    setype: mongod_port_t
    state: present
    reload: yes
  when: jfmc_mongodb_semanage

- name: configure SELinux file contexts for mongodb
  sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    reload: true
    state: present
  with_items:
    - target: "{{ jfmc_mongodb_daemon_bin }}"
      setype: mongod_exec_t
    - target: "{{ jfmc_mongodb_conf_dbPath }}(/.*)?"
      setype: mongod_var_lib_t
    - target: "{{ jfmc_mongodb_conf_pidFile | dirname }}(/.*)?"
      setype: mongod_var_run_t
  when: jfmc_mongodb_semanage

- name: ensure SELinux file context are applied
  shell: restorecon -vr "{{ item }}"
  with_items:
    - "{{ jfmc_mongodb_daemon_bin }}"
    - "{{ jfmc_mongodb_conf_dbPath }}"
    - "{{ jfmc_mongodb_conf_pidFile | dirname }}"
  register: restorecon
  changed_when: restorecon.stdout != ""
  when: jfmc_mongodb_semanage

- name: Check if jfmc service exists
  stat: path=/etc/init.d/mission-control
  register: service_status
  changed_when: false

- name: Run installer shell script
  shell: /opt/jfrog/mission-control/installer/jfmc-redhat-2.1.1/ansible_installJFMC-redhat.sh
  when: not service_status.stat.exists
  notify: Run start script

# TODO: handle /tmp mounted with noexec. (exec in tmp needed by postgres).
