
- name: Enable needed SELinux booleans ({{ item }})
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - nis_enabled
    - httpd_can_network_connect
    - httpd_read_user_content

- name: Allow {{ item.name }} to listen port {{ item.port }} on SELinux
  seport:
    ports: {{ item.port }}
    proto: tcp
    setype: http_port_t
    state: present
  with_items:
    - { port=8080 , name="mission-control"}
    - { port=8085 , name="jfi-scheduler"}
    - { port=8087 , name="jfi-executor"}
    - { port=8090 , name="jfi-core"}
    - { port=8089 , name="jfi-core-ssl"}

- name: Allow php-fpm to read jfi-core files
  sefcontext:
    target: '/var/opt/jfrog/mission-control/jfi-core/_MASTER_/data(/.*)?'
    setype: httpd_sys_content_t
    state: present

- name: Ensure SELinux file context are applied
  shell: restorecon -vr /var/opt/jfrog/mission-control/jfi-core/_MASTER_/data
  register: restorecon
  changed_when: restorecon.stdout != ""